import type { StorageService } from '@africanies/africanies-storage';
import { AFRICANIES_MODE_CONFIG_KEY } from '@africanies/africanies-storage';
import type { ApiClient, QueryParams, ShippingModeReader } from './index.js';

interface ApiResponseModel<T> { success: boolean; message: string | null; data: T | null; errors: unknown; pagination: unknown; status_code: number | null; [key: string]: unknown; }
type ResourceId = null | 'all' | number;
export type ResourceQueryParams = Record<string, string | number | boolean | null | undefined> & { page?: number; size?: number; order?: string };

export const AUTH_FORGOT_PASSWORD_PATH = '/auth/forgot/password';
export const MODE_CONFIG_PATH = '/public/mode/config';
export const COUNTRY_READ_PATH = '/public/country/read';
export const CURRENCY_READ_PATH = '/currency/read';
export const CURRENCY_CREATE_PATH = '/currency/create';
export const CURRENCY_UPDATE_PATH = '/currency/update';
export const CURRENCY_DELETE_PATH = '/currency/delete';
export const DOCUMENT_READ_PATH = '/public/document/read';
export const FILE_READ_PATH = '/file/read';
export const FILE_READ_MULTIPLE_PARAM = 'yes';
export const NOTIFICATION_READ_PATH = '/user/notifications/read';
export const NOTIFICATION_UPDATE_PATH = '/user/notifications/update';
export const PAYMENT_METHOD_READ_PATH = '/payment_method/read';
export const PAYMENT_METHOD_UPDATE_PATH = '/payment_method/update';
export const PLAN_READ_PATH = '/public/plan/read';
export const PRODUCT_READ_PATH = '/product/read';
export const SERVICE_READ_PATH = '/public/service/read';
export const SHIPMENT_METHOD_READ_PATH = '/shipment_method/read';
export const USER_PATH = '/user';
export const USER_CHANGE_PASSWORD_PATH = '/user/change/password';
export const USER_LOGOUT_FROM_ALL_SESSIONS_PATH = '/user/logout-from-all-sessions';
export const WAREHOUSE_READ_PATH = '/warehouse/read';
export const ZONE_READ_PATH = '/zone/read/records';

export function buildResourcePath(basePath: string, id: ResourceId = null): string { const trimmed = basePath.replace(/\/+$/, ''); return id === null ? trimmed : `${trimmed}/${id}`; }
export function buildResourceQueryParams(id: ResourceId, params?: ResourceQueryParams): QueryParams | undefined {
  const { page, size, order, ...rest } = params ?? {}; const out: Record<string, string | number | boolean> = {};
  for (const [key, value] of Object.entries(rest)) if (value !== null && value !== undefined && value !== '') out[key] = value;
  if (id === null) { if (page !== undefined) out.page = page; out.size = size ?? 15; if (order !== undefined) out.order = order; }
  return Object.keys(out).length ? out : undefined;
}
export function resourceCacheTtlMs(id: ResourceId, ttlMs: number): number | undefined { return id === null ? undefined : ttlMs; }
export function mapResourcePayload<T>(id: ResourceId, raw: unknown, mapOne: (raw: unknown) => T, mapMany: (raw: unknown) => T[]): T | T[] | null {
  if (raw == null) return typeof id === 'number' ? null : [];
  if (typeof id === 'number') { const item = Array.isArray(raw) ? raw[0] : raw; return item == null ? null : mapOne(item); }
  return mapMany(raw);
}

export function asString(value: unknown): string { return typeof value === 'string' ? value : value == null ? '' : String(value); }
export function asNullableString(value: unknown): string | null { return value == null ? null : asString(value); }
export function asNumber(value: unknown): number { const number = Number(value); return Number.isFinite(number) ? number : 0; }
export function asNullableNumber(value: unknown): number | null { return value == null || value === '' ? null : asNumber(value); }
export function asBoolean(value: unknown): boolean { return value === true || value === 1 || value === '1' || value === 'true'; }
export function asNullableBoolean(value: unknown): boolean | null { return value == null || value === '' ? null : asBoolean(value); }
export function toFlag01(value: unknown): '1' | '0' { return asBoolean(value) ? '1' : '0'; }
export function mapWireRecord(raw: unknown): Record<string, unknown> { return typeof raw === 'object' && raw !== null && !Array.isArray(raw) ? { ...raw as Record<string, unknown> } : {}; }
export function mapWireList(raw: unknown, mapper: (raw: unknown) => Record<string, unknown> = mapWireRecord): Record<string, unknown>[] { return (Array.isArray(raw) ? raw : raw == null ? [] : [raw]).map(mapper); }

export function mapCountryState(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { name: asString(row.name), state_code: asString(row.state_code ?? row.stateCode) }; }
export function mapCountry(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), name: asString(row.name), iso3: asString(row.iso3), iso2: asString(row.iso2), states: (Array.isArray(row.states) ? row.states : []).map(mapCountryState) }; } export const mapCountryList = (raw: unknown) => mapWireList(raw, mapCountry);
export function mapFileRead(raw: unknown): Record<string, unknown> { const row = mapWireRecord(Array.isArray(raw) ? raw[0] : raw); return { mime_type: asString(row.mime_type ?? row.mimeType), base_64: asString(row.base_64 ?? row.base64), url: asString(row.url) }; } export function mapFileReadList(raw: unknown) { return (Array.isArray(raw) ? raw : raw == null ? [] : [raw]).map(mapFileRead); }
export function mapDocument(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); const nested = row.file_ref ?? row.fileRef; const hasFlat = row.mime_type != null || row.mimeType != null || row.base_64 != null || row.base64 != null || row.url != null; return { id: asNumber(row.id), name: asString(row.name), description: asNullableString(row.description), type: asNullableString(row.type), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), file_ref: isRecord(nested) ? mapFileRead(nested) : hasFlat ? mapFileRead(row) : null }; } export const mapDocumentList = (raw: unknown) => mapWireList(raw, mapDocument);
export function mapPlanPackage(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), plan_id: asNullableNumber(row.plan_id ?? row.planId), company_service_id: asNullableNumber(row.company_service_id ?? row.companyServiceId), name: asString(row.name), metrics: asNullableString(row.metrics), volume: asNullableNumber(row.volume), discount: asNullableString(row.discount), model: asNullableString(row.model), monthly: asNullableString(row.monthly), quarterly: asNullableString(row.quarterly), biannually: asNullableString(row.biannually), annually: asNullableString(row.annually), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt) }; }
export function mapPlan(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), name: asString(row.name), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), packages: (Array.isArray(row.packages) ? row.packages : []).map(mapPlanPackage) }; } export const mapPlanList = (raw: unknown) => mapWireList(raw, mapPlan);
export function mapProduct(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); const numberArray = (value: unknown) => Array.isArray(value) ? value.map(asNumber) : null; const stringArray = (value: unknown) => (Array.isArray(value) ? value : []).map(asString); return { id: asNumber(row.id), account_id: asNullableNumber(row.account_id ?? row.accountId), product_category_id: asNullableNumber(row.product_category_id ?? row.productCategoryId), hs_code: asString(row.hs_code ?? row.hsCode), hs_code_10: asNullableString(row.hs_code_10 ?? row.hsCode10), hs_code_8: asNullableString(row.hs_code_8 ?? row.hsCode8), hs_code_6: asNullableString(row.hs_code_6 ?? row.hsCode6), name: asString(row.name), value: asNumber(row.value), usage: asNumber(row.usage), document_ids: numberArray(row.document_ids ?? row.documentIds), etw_ids: numberArray(row.etw_ids ?? row.etwIds), active: asBoolean(row.active), is_external: asBoolean(row.is_external ?? row.isExternal), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), document_details: stringArray(row.document_details ?? row.documentDetails), etw_document_details: stringArray(row.etw_document_details ?? row.etwDocumentDetails), zone_product_required_documents: Array.isArray(row.zone_product_required_documents ?? row.zoneProductRequiredDocuments) ? row.zone_product_required_documents ?? row.zoneProductRequiredDocuments : [] }; } export const mapProductList = (raw: unknown) => mapWireList(raw, mapProduct);
export function mapService(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), name: asString(row.name), description: asNullableString(row.description), model: asString(row.model), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt) }; } export const mapServiceList = (raw: unknown) => mapWireList(raw, mapService);
export function mapShipmentZone(raw: unknown): Record<string, unknown> | null { return isRecord(raw) ? { id: asNumber(raw.id), name: asString(raw.name), type: asString(raw.type), active: asBoolean(raw.active) } : null; }
export function mapShipmentMethodZoneLink(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), zone_id: asNumber(row.zone_id ?? row.zoneId), shipment_method_id: asNumber(row.shipment_method_id ?? row.shipmentMethodId), active: asBoolean(row.active), mode: row.mode === 'stn' ? 'stn' : 'sfn', zone: mapShipmentZone(row.zone) }; }
export function mapShipmentMethodZonePage(raw: unknown): Record<string, unknown> { if (!isRecord(raw)) return { data: [], current_page: 0, per_page: 0, total: 0, last_page: 0 }; const items = raw.data ?? raw.items; return { data: (Array.isArray(items) ? items : []).map(mapShipmentMethodZoneLink), current_page: asNumber(raw.current_page ?? raw.currentPage), per_page: asNumber(raw.per_page ?? raw.perPage), total: asNumber(raw.total), last_page: asNumber(raw.last_page ?? raw.lastPage) }; }
export function mapShipmentMethod(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); const yesNo = (value: unknown) => typeof value === 'boolean' ? value : asString(value).trim().toLowerCase() === 'yes'; return { id: asNumber(row.id), name: asString(row.name), slug: asString(row.slug), model: asString(row.model), min_delivery_business_day: asNumber(row.min_delivery_business_day ?? row.minDeliveryBusinessDay), max_delivery_business_day: asNumber(row.max_delivery_business_day ?? row.maxDeliveryBusinessDay), notes: asString(row.notes), blacklisted_words: asNullableString(row.blacklisted_words ?? row.blacklistedWords), position: asNumber(row.position), min_weight: asNumber(row.min_weight ?? row.minWeight), max_weight: asNumber(row.max_weight ?? row.maxWeight), max_length: asNumber(row.max_length ?? row.maxLength), max_width: asNumber(row.max_width ?? row.maxWidth), max_height: asNumber(row.max_height ?? row.maxHeight), markup: asNumber(row.markup), surcharge: asNumber(row.surcharge), insurance_benchmark: asNumber(row.insurance_benchmark ?? row.insuranceBenchmark), insurance: asNumber(row.insurance), clearing_handling: asNumber(row.clearing_handling ?? row.clearingHandling), destination: asString(row.destination), sea_only: yesNo(row.sea_only ?? row.seaOnly), currency: asString(row.currency), type: asString(row.type), active: asBoolean(row.active), multiple_rates: asBoolean(row.multiple_rates ?? row.multipleRates), first_shipment_discount: asNumber(row.first_shipment_discount ?? row.firstShipmentDiscount), discount_type: asString(row.discount_type ?? row.discountType), discount_active: asBoolean(row.discount_active ?? row.discountActive), mode: row.mode === 'stn' ? 'stn' : 'sfn', deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), markdown: asNumber(row.markdown), zone_values: mapShipmentMethodZonePage(row.zone_values ?? row.zoneValues) }; } export const mapShipmentMethodList = (raw: unknown) => mapWireList(raw, mapShipmentMethod);
export function mapWarehouseState(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { id: asNumber(raw.id), name: asString(raw.name), state_code: asString(raw.state_code ?? raw.stateCode), country: asString(raw.country), country_code: asString(raw.country_code ?? raw.countryCode) }; }
export function mapWarehouseCountry(raw: unknown): Record<string, unknown> | null { return raw == null ? null : mapCountry(raw); }
export function mapWarehouse(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), partner_id: asNullableNumber(row.partner_id ?? row.partnerId), name: asString(row.name), phone: asString(row.phone), email: asString(row.email), country: mapWarehouseCountry(row.country), api_enabled: asBoolean(row.api_enabled ?? row.apiEnabled), state: mapWarehouseState(row.state), city: asString(row.city), address: asString(row.address), longitude: asNumber(row.longitude), latitude: asNumber(row.latitude), zip_code: asString(row.zip_code ?? row.zipCode), usage: asNumber(row.usage), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), storage_charge: asNumber(row.storage_charge ?? row.storageCharge), storage_period: asNumber(row.storage_period ?? row.storagePeriod), delivery_charge: asNumber(row.delivery_charge ?? row.deliveryCharge), delivery_count: asNumber(row.delivery_count ?? row.deliveryCount), currency: asString(row.currency), etw_shipment_available: asBoolean(row.etw_shipment_available ?? row.etwShipmentAvailable), local: asBoolean(row.local), no_shippo: asBoolean(row.no_shippo ?? row.noShippo), partner: row.partner ?? null }; } export const mapWarehouseList = (raw: unknown) => mapWireList(raw, mapWarehouse);
export function mapZone(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), name: asString(row.name), type: asString(row.type), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt) }; } export const mapZoneList = (raw: unknown) => mapWireList(raw, mapZone);
export function mapNotificationPayload(raw: unknown): Record<string, unknown> { let row = mapWireRecord(raw); if (typeof raw === 'string' && raw.trim()) { try { row = mapWireRecord(JSON.parse(raw) as unknown); } catch { row = {}; } } const userId = row.user_id ?? row.userId; return { user_id: userId == null ? null : asNumber(userId), title: asString(row.title), body: asNullableString(row.body), link: asNullableString(row.link), image: asNullableString(row.image), external_link: asNullableBoolean(row.external_link ?? row.externalLink) }; }
export function mapNotification(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asString(row.id), type: asString(row.type), notifiable_type: asString(row.notifiable_type ?? row.notifiableType), notifiable_id: asNumber(row.notifiable_id ?? row.notifiableId), data: mapNotificationPayload(row.data), read_at: asNullableString(row.read_at ?? row.readAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt) }; } export const mapNotificationList = (raw: unknown) => mapWireList(raw, mapNotification).filter(row => row.id !== '');
export function mapNotificationInboxItem(notification: Record<string, unknown> | null | undefined): Record<string, unknown> { const row = notification ?? mapNotification(null); const data = isRecord(row.data) ? row.data : mapNotificationPayload(null); return { id: asString(row.id), title: asString(data.title), body: data.body ?? undefined, timestamp: row.created_at ?? undefined, read: row.read_at != null && row.read_at !== '', link: data.link ?? undefined, external_link: data.external_link ?? undefined, image: data.image ?? null }; }
export function mapUserCountryState(raw: unknown): Record<string, unknown> | null { return isRecord(raw) ? { name: asNullableString(raw.name), state_code: asNullableString(raw.state_code ?? raw.stateCode) } : null; }
export function mapUserCountry(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { id: asNullableNumber(raw.id), name: asNullableString(raw.name), iso3: asNullableString(raw.iso3), iso2: asNullableString(raw.iso2), states: Array.isArray(raw.states) ? raw.states.map(mapUserCountryState).filter(Boolean) : null }; }
export function mapUserStateLabel(raw: unknown): string | null { if (raw == null) return null; if (typeof raw === 'string') return raw; return isRecord(raw) ? asNullableString(raw.name) : null; }
const enumValue = (value: unknown, choices: readonly string[]) => typeof value === 'string' && choices.includes(value) ? value : null;
export function mapUserPlanPackage(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { id: asNullableNumber(raw.id), plan_id: asNullableNumber(raw.plan_id ?? raw.planId), company_service_id: asNullableNumber(raw.company_service_id ?? raw.companyServiceId), name: asNullableString(raw.name), metrics: asNullableString(raw.metrics), volume: asNullableNumber(raw.volume), discount: asNullableString(raw.discount), model: asNullableString(raw.model), monthly: asNullableString(raw.monthly), quarterly: asNullableString(raw.quarterly), biannually: asNullableString(raw.biannually), annually: asNullableString(raw.annually), active: asNullableBoolean(raw.active), deleted_at: asNullableString(raw.deleted_at ?? raw.deletedAt), created_at: asNullableString(raw.created_at ?? raw.createdAt), updated_at: asNullableString(raw.updated_at ?? raw.updatedAt) }; }
export function mapUserPlan(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { id: asNullableNumber(raw.id), name: asNullableString(raw.name), active: asNullableBoolean(raw.active), deleted_at: asNullableString(raw.deleted_at ?? raw.deletedAt), created_at: asNullableString(raw.created_at ?? raw.createdAt), updated_at: asNullableString(raw.updated_at ?? raw.updatedAt), packages: Array.isArray(raw.packages) ? raw.packages.map(mapUserPlanPackage).filter(Boolean) : null }; }
export function mapUserGatewayPayload(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { authorization_url: asNullableString(raw.authorization_url ?? raw.authorizationUrl), access_code: asNullableString(raw.access_code ?? raw.accessCode), reference: asNullableString(raw.reference), redirect_url: asNullableString(raw.redirect_url ?? raw.redirectUrl) }; }
export function mapUserPaymentPayload(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { url: asNullableString(raw.url), redirect_url: asNullableString(raw.redirect_url ?? raw.redirectUrl), gateway_payload: mapUserGatewayPayload(raw.gateway_payload ?? raw.gatewayPayload), reference: asNullableString(raw.reference) }; }
export function mapUserSubscription(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { id: asNullableNumber(raw.id), user_id: asNullableNumber(raw.user_id ?? raw.userId), plan_id: asNullableNumber(raw.plan_id ?? raw.planId), account_id: asNullableNumber(raw.account_id ?? raw.accountId), reference: asNullableString(raw.reference), process_url: asNullableString(raw.process_url ?? raw.processUrl), reference_salt: asNullableString(raw.reference_salt ?? raw.referenceSalt), amount: asNullableString(raw.amount), currency: asNullableString(raw.currency), payment_amount: asNullableString(raw.payment_amount ?? raw.paymentAmount), payment_currency: asNullableString(raw.payment_currency ?? raw.paymentCurrency), coupon_id: asNullableNumber(raw.coupon_id ?? raw.couponId), coupon_discount: asNullableString(raw.coupon_discount ?? raw.couponDiscount), coupon_amount: asNullableString(raw.coupon_amount ?? raw.couponAmount), payment_payload: asNullableString(raw.payment_payload ?? raw.paymentPayload), plan_type: enumValue(raw.plan_type ?? raw.planType, ['monthly', 'quarterly', 'biannually', 'annually']), used: asNullableBoolean(raw.used), deleted_at: asNullableString(raw.deleted_at ?? raw.deletedAt), created_at: asNullableString(raw.created_at ?? raw.createdAt), updated_at: asNullableString(raw.updated_at ?? raw.updatedAt) }; }
export function mapUserBusinessAccount(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { id: asNullableNumber(raw.id), user_id: asNullableNumber(raw.user_id ?? raw.userId), plan_id: asNullableNumber(raw.plan_id ?? raw.planId), name: asNullableString(raw.name), account_email: asNullableString(raw.account_email ?? raw.accountEmail), plan_type: enumValue(raw.plan_type ?? raw.planType, ['monthly', 'quarterly', 'biannually', 'annually']), first_payment: asNullableBoolean(raw.first_payment ?? raw.firstPayment), is_whitelisted: asNullableBoolean(raw.is_whitelisted ?? raw.isWhitelisted), no_state_validation: asNullableBoolean(raw.no_state_validation ?? raw.noStateValidation), show_waybill: asNullableBoolean(raw.show_waybill ?? raw.showWaybill), notify_api_shipment: asNullableBoolean(raw.notify_api_shipment ?? raw.notifyApiShipment), active: asNullableBoolean(raw.active), expires_at: asNullableString(raw.expires_at ?? raw.expiresAt), deleted_at: asNullableString(raw.deleted_at ?? raw.deletedAt), created_at: asNullableString(raw.created_at ?? raw.createdAt), updated_at: asNullableString(raw.updated_at ?? raw.updatedAt), type: enumValue(raw.type, ['business', 'individual']), days_left: asNullableNumber(raw.days_left ?? raw.daysLeft), plan: mapUserPlan(raw.plan), subscription: mapUserSubscription(raw.subscription) }; }
export function mapUserAccountManager(raw: unknown): Record<string, unknown> | null { if (!isRecord(raw)) return null; return { id: asNullableNumber(raw.id), user_id: asNullableNumber(raw.user_id ?? raw.userId), manager_id: asNullableNumber(raw.manager_id ?? raw.managerId), account_id: asNullableNumber(raw.account_id ?? raw.accountId), name: asNullableString(raw.name), email: asNullableString(raw.email), phone: asNullableString(raw.phone), created_at: asNullableString(raw.created_at ?? raw.createdAt), updated_at: asNullableString(raw.updated_at ?? raw.updatedAt), deleted_at: asNullableString(raw.deleted_at ?? raw.deletedAt) }; }
export function mapUser(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); const nullableFlag = (value: unknown) => value == null || value === '' ? null : toFlag01(value); return { id: asNullableNumber(row.id), central_id: asNullableString(row.central_id ?? row.centralId), name: asNullableString(row.name), first_name: asNullableString(row.first_name ?? row.firstName), middle_name: asNullableString(row.middle_name ?? row.middleName), last_name: asNullableString(row.last_name ?? row.lastName), email: asNullableString(row.email), phone: asNullableString(row.phone), unit_number: asNullableString(row.unit_number ?? row.unitNumber), referral_code: asNullableString(row.referral_code ?? row.referralCode), old_unit_number: asNullableString(row.old_unit_number ?? row.oldUnitNumber), account_email: asNullableString(row.account_email ?? row.accountEmail), two_factor: asNullableBoolean(row.two_factor ?? row.twoFactor), default_pin: asNullableBoolean(row.default_pin ?? row.defaultPin), model: enumValue(row.model, ['App\\Models\\Customer', 'App\\Models\\Admin']), country: mapUserCountry(row.country), state: mapUserStateLabel(row.state), email_verified_at: asNullableString(row.email_verified_at ?? row.emailVerifiedAt), phone_verified_at: asNullableString(row.phone_verified_at ?? row.phoneVerifiedAt), kyc_verified_at: asNullableString(row.kyc_verified_at ?? row.kycVerifiedAt), passport_verified_at: asNullableString(row.passport_verified_at ?? row.passportVerifiedAt), suspended_at: asNullableString(row.suspended_at ?? row.suspendedAt), deactivated_at: asNullableString(row.deactivated_at ?? row.deactivatedAt), active: asNullableBoolean(row.active), default_password: asNullableBoolean(row.default_password ?? row.defaultPassword), type: enumValue(row.type, ['business', 'individual']), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), last_login_at: asNullableString(row.last_login_at ?? row.lastLoginAt), socialite_signup: nullableFlag(row.socialite_signup ?? row.socialiteSignup), form_signup: nullableFlag(row.form_signup ?? row.formSignup), main_region: asNullableString(row.main_region ?? row.mainRegion), shipping_type: enumValue(row.shipping_type ?? row.shippingType, ['instant', 'consolidation']), accounts: Array.isArray(row.accounts) ? row.accounts : null, business_account: mapUserBusinessAccount(row.business_account ?? row.businessAccount), account_manager: mapUserAccountManager(row.account_manager ?? row.accountManager) }; }
export function mapRegionConfig(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { dimension_unit: row.dimension_unit === 'inches' || row.dimensionUnit === 'inches' ? 'inches' : 'cm', mass_unit: row.mass_unit === 'LBS' || row.massUnit === 'LBS' ? 'LBS' : 'KG', currency: row.currency === 'USD' ? 'USD' : 'NGN', currency_symbol: asString(row.currency_symbol ?? row.currencySymbol) }; }
export function mapModeRegions(raw: unknown): Record<string, Record<string, unknown>> { const result: Record<string, Record<string, unknown>> = {}; for (const [key, value] of Object.entries(mapWireRecord(raw))) result[key] = mapRegionConfig(value); return result; }
const defaultRegion = () => ({ dimension_unit: 'cm', mass_unit: 'KG', currency: 'NGN', currency_symbol: '' });
export function mapModeConfigData(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); const sfn = mapModeRegions(row.sfn); const stn = mapModeRegions(row.stn); return { sfn: { default: sfn.default ?? defaultRegion(), ng: sfn.ng ?? sfn.default ?? defaultRegion() }, stn: { default: stn.default ?? defaultRegion(), us: stn.us ?? stn.default ?? defaultRegion(), cn: stn.cn ?? stn.default ?? defaultRegion(), gb: stn.gb ?? stn.default ?? defaultRegion() } }; }
export function isModeConfigData(value: unknown): boolean { const row = mapWireRecord(value); const sfn = mapWireRecord(row.sfn); const stn = mapWireRecord(row.stn); return isRecord(sfn.default) && isRecord(stn.default); }
export function resolveModeRegionConfig(config: Record<string, unknown> | null | undefined, mode: 'sfn' | 'stn', countryCode: string | null | undefined): Record<string, unknown> { const regions = mapWireRecord(config?.[mode]); const key = asString(countryCode).toLowerCase(); const region = key && key !== 'default' ? regions[key] : undefined; return isRecord(region) ? region : isRecord(regions.default) ? regions.default : defaultRegion(); }

export function toCurrencyFlag01(value: unknown): '0' | '1' { return toFlag01(value); }
export function mapCurrencyPaymentMethodPivot(raw: unknown): Record<string, number> { const row = mapWireRecord(raw); return { currency_id: asNumber(row.currency_id ?? row.currencyId), payment_method_id: asNumber(row.payment_method_id ?? row.paymentMethodId) }; }
export function mapCurrencyPaymentMethod(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), name: asString(row.name), model: asString(row.model), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), pivot: mapCurrencyPaymentMethodPivot(row.pivot) }; }
export function mapCurrency(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); const naira = asBoolean(row.is_naira_greater ?? row.isNairaGreater ?? row.is_local_currency_greater ?? row.isLocalCurrencyGreater); const methods = row.payment_methods ?? row.paymentMethods; return { id: asNumber(row.id), name: asString(row.name), short_code: asString(row.short_code ?? row.shortCode), division_rate: asString(row.division_rate ?? row.divisionRate), multiplication_rate: asString(row.multiplication_rate ?? row.multiplicationRate), is_local_currency_greater: naira, is_naira_greater: naira, active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), payment_methods: Array.isArray(methods) ? methods.map(mapCurrencyPaymentMethod) : [] }; }
export const mapCurrencyList = (raw: unknown) => mapWireList(raw, mapCurrency);
export function toCurrencyCreateBody(body: Record<string, unknown> | null | undefined) { return { name: asString(body?.name).trim(), short_code: asString(body?.short_code).trim(), multiplication_rate: asString(body?.multiplication_rate), division_rate: asString(body?.division_rate), active: toFlag01(body?.active), is_naira_greater: toFlag01(body?.is_naira_greater), payment_method_ids: Array.isArray(body?.payment_method_ids) ? body.payment_method_ids.map(asNumber) : [] }; }
export function toCurrencyUpdateBody(body: Record<string, unknown> | null | undefined) { return { id: asNumber(body?.id), multiplication_rate: asString(body?.multiplication_rate), division_rate: asString(body?.division_rate), active: toFlag01(body?.active), is_naira_greater: toFlag01(body?.is_naira_greater), payment_method_ids: Array.isArray(body?.payment_method_ids) ? body.payment_method_ids.map(asNumber) : [] }; }
export function toCurrencyDeleteBody(body: number | { id?: unknown } | null | undefined) { return { id: asNumber(typeof body === 'number' ? body : body?.id) }; }
export function toPaymentMethodFlag01(value: unknown): '0' | '1' { return toFlag01(value); }
export function mapPaymentMethodCurrency(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); const mapped = mapCurrency(row); return { id: mapped.id, name: mapped.name, short_code: mapped.short_code, division_rate: mapped.division_rate, multiplication_rate: mapped.multiplication_rate, is_local_currency_greater: mapped.is_local_currency_greater, is_naira_greater: mapped.is_naira_greater, active: mapped.active, deleted_at: mapped.deleted_at, created_at: mapped.created_at, updated_at: mapped.updated_at, pivot: mapCurrencyPaymentMethodPivot(row.pivot) }; }
export function mapPaymentMethod(raw: unknown): Record<string, unknown> { const row = mapWireRecord(raw); return { id: asNumber(row.id), name: asString(row.name), model: asString(row.model), active: asBoolean(row.active), deleted_at: asNullableString(row.deleted_at ?? row.deletedAt), created_at: asNullableString(row.created_at ?? row.createdAt), updated_at: asNullableString(row.updated_at ?? row.updatedAt), currencies: Array.isArray(row.currencies) ? row.currencies.map(mapPaymentMethodCurrency) : [] }; }
export const mapPaymentMethodList = (raw: unknown) => mapWireList(raw, mapPaymentMethod);
export function toPaymentMethodUpdateBody(body: Record<string, unknown>) { return { id: asNumber(body?.id), name: asString(body?.name), model: asString(body?.model), active: toFlag01(body?.active) }; }

async function envelope<T>(promise: Promise<unknown>): Promise<ApiResponseModel<T>> { const value = await promise; if (isRecord(value) && typeof value.success === 'boolean' && 'data' in value) return value as unknown as ApiResponseModel<T>; return { success: true, message: null, data: value as T, errors: null, pagination: null, status_code: 200 }; }
async function apiGet<T>(api: ApiClient, path: string, query?: QueryParams, cache?: number): Promise<ApiResponseModel<T>> { return envelope<T>(api.get(path, { query, cache: cache ?? false, normalize: false })); }
async function apiWrite<T>(api: ApiClient, method: string, path: string, body: unknown, query?: QueryParams): Promise<ApiResponseModel<T>> { return envelope<T>(api.request(method, path, body, { query, normalize: false })); }

class ResourceService {
  constructor(protected readonly api: ApiClient, private readonly path: string, private readonly mapOne: (raw: unknown) => Record<string, unknown>, private readonly mapMany: (raw: unknown) => Record<string, unknown>[]) {}
  async read(id: ResourceId = null, params?: ResourceQueryParams): Promise<ApiResponseModel<Record<string, unknown> | Record<string, unknown>[]>> { const res = await apiGet<unknown>(this.api, buildResourcePath(this.path, id), buildResourceQueryParams(id, params), resourceCacheTtlMs(id, 300_000)); return { ...res, data: mapResourcePayload(id, res.data, this.mapOne, this.mapMany) }; }
  readPage(params?: ResourceQueryParams) { return this.read(null, params) as Promise<ApiResponseModel<Record<string, unknown>[]>>; }
  readAll(params?: ResourceQueryParams) { return this.read('all', params) as Promise<ApiResponseModel<Record<string, unknown>[]>>; }
  readById(id: number, params?: ResourceQueryParams) { return this.read(id, params) as Promise<ApiResponseModel<Record<string, unknown>>>; }
}

export class CountryService extends ResourceService { constructor(api: ApiClient) { super(api, COUNTRY_READ_PATH, mapCountry, mapCountryList); } }
export class DocumentService extends ResourceService { constructor(api: ApiClient) { super(api, DOCUMENT_READ_PATH, mapDocument, mapDocumentList); } }
export class PlanService extends ResourceService { constructor(api: ApiClient) { super(api, PLAN_READ_PATH, mapPlan, mapPlanList); } }
export class ProductService extends ResourceService { constructor(api: ApiClient) { super(api, PRODUCT_READ_PATH, mapProduct, mapProductList); } }
export class ServiceService extends ResourceService { constructor(api: ApiClient) { super(api, SERVICE_READ_PATH, mapService, mapServiceList); } }
export class ShipmentMethodService extends ResourceService { constructor(api: ApiClient) { super(api, SHIPMENT_METHOD_READ_PATH, mapShipmentMethod, mapShipmentMethodList); } }
export class WarehouseService extends ResourceService { constructor(api: ApiClient) { super(api, WAREHOUSE_READ_PATH, mapWarehouse, mapWarehouseList); } }
export class ZoneService extends ResourceService { constructor(api: ApiClient) { super(api, ZONE_READ_PATH, mapZone, mapZoneList); } }
export class CurrencyService extends ResourceService {
  constructor(api: ApiClient) { super(api, CURRENCY_READ_PATH, mapCurrency, mapCurrencyList); }
  async create(body: Record<string, unknown>) { const result = await apiWrite(this.api, 'POST', CURRENCY_CREATE_PATH, toCurrencyCreateBody(body)); this.api.cache.clear(); return result; }
  async update(body: Record<string, unknown>) { const result = await apiWrite(this.api, 'PUT', CURRENCY_UPDATE_PATH, toCurrencyUpdateBody(body)); this.api.cache.clear(); return result; }
  async remove(body: number | { id?: unknown }) { const result = await apiWrite(this.api, 'DELETE', CURRENCY_DELETE_PATH, toCurrencyDeleteBody(body)); this.api.cache.clear(); return result; }
}
export class PaymentMethodService extends ResourceService {
  constructor(api: ApiClient) { super(api, PAYMENT_METHOD_READ_PATH, mapPaymentMethod, mapPaymentMethodList); }
  async update(body: Record<string, unknown>) { const result = await apiWrite(this.api, 'PUT', PAYMENT_METHOD_UPDATE_PATH, toPaymentMethodUpdateBody(body)); this.api.cache.clear(); return result; }
}
export class AuthService { constructor(private readonly api: ApiClient) {} forgot(email: string) { return apiWrite(this.api, 'POST', AUTH_FORGOT_PASSWORD_PATH, { email: asString(email).trim() }); } }
export class UserService { constructor(private readonly api: ApiClient) {} async me() { const res = await apiGet<unknown>(this.api, USER_PATH); return { ...res, data: res.data == null ? null : mapUser(res.data) }; } changePassword(body: Record<string, unknown>) { return apiWrite(this.api, 'POST', USER_CHANGE_PASSWORD_PATH, { current_password: asString(body?.current_password), password: asString(body?.password), password_confirmation: asString(body?.password_confirmation) }); } logoutFromAllSessions() { return apiWrite(this.api, 'POST', USER_LOGOUT_FROM_ALL_SESSIONS_PATH, {}); } }
export class FileService { constructor(private readonly api: ApiClient) {} read(ref: string) { return this.readByBody({ ref }); } readMultiple(ref: string) { return this.readByBodyMultiple({ ref }); } async readByBody(body: { ref?: unknown }) { const res = await apiWrite<unknown>(this.api, 'POST', FILE_READ_PATH, { ref: asString(body?.ref) }); return { ...res, data: res.data == null ? null : mapFileRead(res.data) }; } async readByBodyMultiple(body: { ref?: unknown }) { const res = await apiWrite<unknown>(this.api, 'POST', FILE_READ_PATH, { ref: asString(body?.ref) }, { multiple: FILE_READ_MULTIPLE_PARAM }); return { ...res, data: res.data == null ? null : mapFileReadList(res.data) }; } }
export class NotificationService {
  constructor(private readonly api: ApiClient) {}
  async read(id: null | 'all' = null, params?: ResourceQueryParams) { try { const query = id === null ? { ...params, size: params?.size ?? 30 } : params; const res = await apiGet<unknown>(this.api, buildResourcePath(NOTIFICATION_READ_PATH, id), buildResourceQueryParams(id, query)); return { ...res, data: mapResourcePayload(id, res.data, mapNotification, mapNotificationList) as Record<string, unknown>[] | null }; } catch { return { success: false, message: null, data: [], errors: null, pagination: null, status_code: null }; } }
  readPage(params?: ResourceQueryParams) { return this.read(null, params); } readAll(params?: ResourceQueryParams) { return this.read('all', params); }
  async readOne(id: string) { const res = await apiGet<unknown>(this.api, `${NOTIFICATION_READ_PATH}/${encodeURIComponent(asString(id).trim())}`); return { ...res, data: res.data == null ? null : mapNotification(Array.isArray(res.data) ? res.data[0] : res.data) }; }
  markRead(id?: string) { return apiWrite(this.api, 'PUT', NOTIFICATION_UPDATE_PATH, id ? { id: asString(id) } : {}); }
}

export class ModeConfigService {
  private config: Record<string, unknown> | null;
  private loading = false;
  constructor(private readonly api: ApiClient, private readonly storage: StorageService, private readonly shippingMode: ShippingModeReader) { const stored = storage.get<unknown>(AFRICANIES_MODE_CONFIG_KEY); this.config = isModeConfigData(stored) ? stored as Record<string, unknown> : null; }
  getConfig() { return this.config; } isLoading() { return this.loading; }
  async loadConfig() { this.loading = true; try { const res = await apiGet<Record<string, unknown>>(this.api, MODE_CONFIG_PATH); if (res.success && isRecord(res.data)) { this.config = mapModeConfigData(res.data); this.storage.set(AFRICANIES_MODE_CONFIG_KEY, this.config); } return res; } finally { this.loading = false; } }
  getRegionConfig(countryCode: string | null | undefined, appType = this.shippingMode.getMode()): Record<string, unknown> | null { return this.config ? resolveModeRegionConfig(this.config, appType, countryCode) : null; }
}

export interface FilterSelectOption { value: string; label: string; prefixText?: string; prefixImageUrl?: string; }
export type FilterOptionLists = Record<string, FilterSelectOption[]>;
export interface FilterField { key: string; type: string; optionsSource?: string | null; options?: Array<{ value: string; label: string }>; }
export interface FilterConfig { fields?: FilterField[] | null; }
export function collectResolvableSelectFields(config: FilterConfig | null | undefined): FilterField[] { return (config?.fields ?? []).filter(field => field.type === 'select' && field.optionsSource != null && field.optionsSource !== 'static'); }
export function collectFilterOptionsSources(config: FilterConfig): string[] { return [...new Set(collectResolvableSelectFields(config).map(field => field.optionsSource as string))]; }
export function mapWarehouseFilterOptions(rows: Array<Record<string, unknown>> | null | undefined): FilterSelectOption[] { return (rows ?? []).map(row => ({ value: String(row.id), label: asString(row.name) })); }
export function mapShipmentMethodFilterOptions(rows: Array<Record<string, unknown>> | null | undefined): FilterSelectOption[] { return (rows ?? []).map(row => ({ value: String(row.id), label: asString(row.name) })); }
export function mergeFilterOptionLists(resolved: FilterOptionLists, overrides?: FilterOptionLists | null): FilterOptionLists { return overrides ? { ...resolved, ...overrides } : { ...resolved }; }
export class FilterOptionsResolver {
  constructor(private readonly warehouses: WarehouseService, private readonly shipmentMethods: ShipmentMethodService) {}
  async resolveField(field: FilterField): Promise<FilterSelectOption[]> {
    if (field.type !== 'select' || field.optionsSource == null || field.optionsSource === 'static') return (field.options ?? []).map(option => ({ value: option.value, label: option.label }));
    if (field.optionsSource === 'warehouses') { const res = await this.warehouses.readAll(); return res.success ? mapWarehouseFilterOptions(res.data) : []; }
    if (field.optionsSource === 'shipmentMethods') { const res = await this.shipmentMethods.readAll(); return res.success ? mapShipmentMethodFilterOptions(res.data) : []; }
    return [];
  }
  async resolve(config: FilterConfig): Promise<FilterOptionLists> {
    const fields = collectResolvableSelectFields(config); const sourceResults = new Map<string, FilterSelectOption[]>();
    await Promise.all([...new Set(fields.map(field => field.optionsSource as string))].filter(source => source === 'warehouses' || source === 'shipmentMethods').map(async source => { sourceResults.set(source, await this.resolveField({ key: source, type: 'select', optionsSource: source })); }));
    const result: FilterOptionLists = {}; for (const field of fields) { const options = sourceResults.get(field.optionsSource as string); if (options) result[field.key] = options; } return result;
  }
}

export interface OverlayHandle { close(): void; afterClosed(listener: () => void): () => void; }
export interface OverlayOpener { open(component: unknown, options: { data: Record<string, string> }): OverlayHandle; }
export interface OverlayRouteEntry { component: unknown; overlay: 'modal' | 'drawer'; }
export interface OverlayRouteConfig { paramKey: string; routes: Record<string, OverlayRouteEntry>; }
/** Router-neutral query adapter. Hosts may implement it with History API or their router. */
export interface QueryRouteAdapter { subscribe(listener: (params: URLSearchParams) => void): () => void; replace(params: URLSearchParams): void | Promise<void>; current(): URLSearchParams; }
interface OpenOverlayState { value: string; handle: OverlayHandle; closingFromUrl: boolean; unsubscribeClosed: () => void; }
export class RouteOverlayService {
  private readonly openByKey = new Map<string, OpenOverlayState>();
  private readonly unsubscribeRoute: () => void;
  constructor(private readonly route: QueryRouteAdapter, private readonly configs: readonly OverlayRouteConfig[], private readonly modal?: OverlayOpener, private readonly drawer?: OverlayOpener) { this.unsubscribeRoute = route.subscribe(params => this.sync(params)); this.sync(route.current()); }
  destroy(): void { this.unsubscribeRoute(); for (const [key, state] of [...this.openByKey]) { state.closingFromUrl = true; state.handle.close(); this.teardown(key); } }
  private sync(params: URLSearchParams): void { for (const config of this.configs) this.syncConfig(config, params); }
  private syncConfig(config: OverlayRouteConfig, params: URLSearchParams): void {
    const value = params.get(config.paramKey); const current = this.openByKey.get(config.paramKey);
    if (!value) { if (current) { current.closingFromUrl = true; current.handle.close(); this.teardown(config.paramKey); } return; }
    const entry = config.routes[value]; if (!entry || current?.value === value) return;
    if (current) { current.closingFromUrl = true; current.handle.close(); this.teardown(config.paramKey); }
    const opener = entry.overlay === 'modal' ? this.modal : this.drawer; if (!opener) return;
    const data: Record<string, string> = {}; for (const [key, sibling] of params) if (key !== config.paramKey) data[key] = sibling;
    const handle = opener.open(entry.component, { data });
    const state: OpenOverlayState = { value, handle, closingFromUrl: false, unsubscribeClosed: () => {} };
    state.unsubscribeClosed = handle.afterClosed(() => { const open = this.openByKey.get(config.paramKey); if (!open || open.handle !== handle) return; const fromUrl = open.closingFromUrl; this.teardown(config.paramKey); if (!fromUrl) { const next = this.route.current(); next.delete(config.paramKey); void this.route.replace(next); } });
    this.openByKey.set(config.paramKey, state);
  }
  private teardown(key: string): void { const state = this.openByKey.get(key); if (!state) return; state.unsubscribeClosed(); this.openByKey.delete(key); }
}
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
