type HTMLElementConstructor = typeof HTMLElement;
const HTMLElementBase: HTMLElementConstructor = (globalThis.HTMLElement ?? class {}) as HTMLElementConstructor;
const escapeHtml = (value: unknown): string => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export interface GooglePlacesConfig { apiKey: string; region?: string; language?: string; }
export interface AddressPrediction { placeId: string; description: string; mainText?: string; secondaryText?: string; }
export interface AddressComponent { longName: string; shortName: string; types: string[]; }
export interface AddressPlace { placeId: string; formattedAddress: string; name?: string; lat?: number; lng?: number; streetNumber?: string; route?: string; locality?: string; administrativeAreaLevel1?: string; administrativeAreaLevel1Code?: string; country?: string; countryCode?: string; postalCode?: string; landmark?: string; addressComponents?: AddressComponent[]; }
export interface GooglePlacesServiceOptions { config: GooglePlacesConfig; fetch: typeof globalThis.fetch; }
export class GooglePlacesService {
  constructor(private readonly options: GooglePlacesServiceOptions) {}
  async getPredictions(query: string, countries?: string[]): Promise<AddressPrediction[]> {
    const input = query.trim(); const key = this.options.config.apiKey.trim(); if (!input || !key) return [];
    const regions = (countries?.length ? countries : this.options.config.region ? [this.options.config.region] : []).map(value => value.trim().toLowerCase()).filter(Boolean);
    const body: Record<string, unknown> = { input }; if (regions.length) body.includedRegionCodes = regions; if (this.options.config.language?.trim()) body.languageCode = this.options.config.language.trim();
    const data = await this.request<{ suggestions?: Array<{ placePrediction?: { placeId?: string; text?: { text?: string }; structuredFormat?: { mainText?: { text?: string }; secondaryText?: { text?: string } } } }> }>('https://places.googleapis.com/v1/places:autocomplete', { method: 'POST', body: JSON.stringify(body) }, 'suggestions.placePrediction.placeId,suggestions.placePrediction.text,suggestions.placePrediction.structuredFormat,suggestions.placePrediction.types');
    return (data.suggestions ?? []).flatMap(item => { const prediction = item.placePrediction; const placeId = prediction?.placeId?.trim(); const description = prediction?.text?.text?.trim() || prediction?.structuredFormat?.mainText?.text?.trim(); if (!placeId || !description) return []; return [{ placeId, description, mainText: prediction?.structuredFormat?.mainText?.text?.trim(), secondaryText: prediction?.structuredFormat?.secondaryText?.text?.trim() }]; });
  }
  async getPlaceDetails(placeId: string): Promise<AddressPlace | null> {
    const id = placeId.trim().replace(/^places\//, ''); if (!id || !this.options.config.apiKey.trim()) return null;
    const details = await this.request<{ id?: string; displayName?: { text?: string }; formattedAddress?: string; addressComponents?: Array<{ longText?: string; shortText?: string; types?: string[] }>; location?: { latitude?: number; longitude?: number } }>(`https://places.googleapis.com/v1/places/${encodeURIComponent(id)}`, { method: 'GET' }, 'id,displayName,formattedAddress,addressComponents,location');
    const components = (details.addressComponents ?? []).map(item => ({ longName: item.longText ?? '', shortName: item.shortText ?? '', types: item.types ?? [] })); const find = (type: string): AddressComponent | undefined => components.find(item => item.types.includes(type)); const locality = find('locality') ?? find('postal_town') ?? find('sublocality') ?? find('neighborhood') ?? find('administrative_area_level_2'); const country = find('country'); const landmark = find('landmark') ?? find('neighborhood') ?? find('sublocality') ?? find('premise') ?? find('point_of_interest');
    return { placeId: details.id || id, formattedAddress: details.formattedAddress ?? '', name: details.displayName?.text?.trim() || undefined, lat: details.location?.latitude, lng: details.location?.longitude, streetNumber: find('street_number')?.longName, route: find('route')?.longName, locality: locality?.longName, administrativeAreaLevel1: find('administrative_area_level_1')?.longName, administrativeAreaLevel1Code: find('administrative_area_level_1')?.shortName, country: country?.longName, countryCode: country?.shortName, postalCode: find('postal_code')?.longName, landmark: landmark?.longName || undefined, addressComponents: components.length ? components : undefined };
  }
  async request<T>(url: string, init: RequestInit, mask: string): Promise<T> { const response = await this.options.fetch(url, { ...init, headers: { 'Content-Type': 'application/json', 'X-Goog-Api-Key': this.options.config.apiKey.trim(), 'X-Goog-FieldMask': mask, ...init.headers } }); if (!response.ok) { let message = ''; try { message = ((await response.json()) as { error?: { message?: string } }).error?.message?.trim() ?? ''; } catch { /* response was not JSON */ } throw new Error(message || ({ 401: 'Authentication failed. Please check your API key.', 403: 'Access denied. Enable Places API (New) for this key.', 429: 'Too many requests. Please try again in a moment.' } as Record<number, string>)[response.status] || `Places API request failed (${response.status}).`); } return response.json() as Promise<T>; }
}
export const provideGooglePlaces = (config: GooglePlacesConfig, fetch: typeof globalThis.fetch): GooglePlacesService => new GooglePlacesService({ config, fetch });

export class AddressInputComponent extends HTMLElementBase {
  static readonly observedAttributes = ['label', 'placeholder', 'disabled', 'error', 'countries']; service: GooglePlacesService | null = null; #root: ShadowRoot | null = null; #timer: ReturnType<typeof globalThis.setTimeout> | null = null; #input: HTMLInputElement | null = null; #predictions: AddressPrediction[] = []; value: AddressPlace | null = null;
  connectedCallback(): void { if (!this.#root) this.#root = this.attachShadow({ mode: 'open' }); this.render(); } disconnectedCallback(): void { if (this.#timer) clearTimeout(this.#timer); this.#input?.removeEventListener('input', this.onInput); }
  onInput = (): void => { if (this.#timer) clearTimeout(this.#timer); this.#timer = setTimeout(async () => { this.#predictions = await (this.service?.getPredictions(this.#input?.value ?? '', (this.getAttribute('countries') ?? '').split(',').filter(Boolean)) ?? Promise.resolve([])); this.render(); }, 300); };
  async select(placeId: string): Promise<void> { const place = await this.service?.getPlaceDetails(placeId); if (!place) return; this.value = place; this.dispatchEvent(new CustomEvent('change', { bubbles: true, composed: true, detail: place })); this.#predictions = []; this.render(); }
  render(): void { if (!this.#root) return; const error = this.getAttribute('error'); this.#root.innerHTML = `<label>${escapeHtml(this.getAttribute('label') ?? 'Address')}<input role="combobox" aria-autocomplete="list" aria-expanded="${this.#predictions.length > 0}"${error ? ' aria-invalid="true" aria-describedby="address-error"' : ''}${this.hasAttribute('disabled') ? ' disabled' : ''} placeholder="${escapeHtml(this.getAttribute('placeholder') ?? '')}"></label><ul role="listbox">${this.#predictions.map(item => `<li><button type="button" role="option" data-place="${escapeHtml(item.placeId)}">${escapeHtml(item.description)}</button></li>`).join('')}</ul>${error ? `<div id="address-error" role="alert">${escapeHtml(error)}</div>` : ''}`; this.#input = this.#root.querySelector('input'); if (this.value) this.#input!.value = this.value.formattedAddress; this.#input?.addEventListener('input', this.onInput); this.#root.querySelectorAll<HTMLButtonElement>('[data-place]').forEach(button => button.addEventListener('click', () => void this.select(button.dataset.place ?? ''))); }
}

const parseAccept = (accept: string): string[] => accept.split(',').map(token => token.trim().toLowerCase()).filter(Boolean);
export function fileMatchesAccept(file: Pick<File, 'name' | 'type'>, accept: string): boolean { const tokens = parseAccept(accept); if (!tokens.length) return true; const name = file.name.toLowerCase(); const type = (file.type || '').toLowerCase(); return tokens.some(token => token.startsWith('.') ? name.endsWith(token) : token.endsWith('/*') ? type.startsWith(token.slice(0, -1)) : type === token); }
export function acceptLabels(accept: string): string[] { const labels = parseAccept(accept).map(token => token === 'image/*' ? 'Images' : token === 'application/pdf' || token === '.pdf' ? 'PDF' : token.startsWith('.') ? token.slice(1).toUpperCase() : token.endsWith('/*') ? `${token.slice(0, -2)} files` : (token.split('/')[1] ?? token).toUpperCase()); return [...new Set(labels)]; }
export function fileExtensionLabel(name: string): string { const index = name.lastIndexOf('.'); return index < 0 || index === name.length - 1 ? '' : name.slice(index + 1).toUpperCase().slice(0, 5); }
export interface FileUploadResult { file: File; previewUrl: string | null; isImage: boolean; }
// @ts-expect-error -- DOM typings assume createObjectURL exists and reserve parameterless remove(); this element capability-checks the former and removes a preview by index.
export class FileUploadComponent extends HTMLElementBase { static readonly observedAttributes = ['accept', 'multiple', 'capture', 'disabled']; #root: ShadowRoot | null = null; #results: FileUploadResult[] = []; #urls = new Set<string>(); get value(): readonly FileUploadResult[] { return this.#results; } connectedCallback(): void { if (!this.#root) this.#root = this.attachShadow({ mode: 'open' }); this.render(); } disconnectedCallback(): void { this.clear(); } addFiles(files: Iterable<File>): void { const accept = this.getAttribute('accept') ?? ''; for (const file of files) { if (!fileMatchesAccept(file, accept)) { this.dispatchEvent(new CustomEvent('file-rejected', { bubbles: true, composed: true, detail: { file } })); continue; } const isImage = file.type.startsWith('image/'); const previewUrl = isImage && globalThis.URL?.createObjectURL ? URL.createObjectURL(file) : null; if (previewUrl) this.#urls.add(previewUrl); this.#results.push({ file, previewUrl, isImage }); if (!this.hasAttribute('multiple')) break; } this.dispatchEvent(new CustomEvent('change', { bubbles: true, composed: true, detail: this.#results })); this.render(); } remove(index: number): void { const result = this.#results[index]; if (result?.previewUrl) { URL.revokeObjectURL(result.previewUrl); this.#urls.delete(result.previewUrl); } this.#results.splice(index, 1); this.render(); } clear(): void { for (const url of this.#urls) URL.revokeObjectURL(url); this.#urls.clear(); this.#results = []; } render(): void { if (!this.#root) return; this.#root.innerHTML = `<label part="dropzone">Choose files<input type="file"${this.hasAttribute('multiple') ? ' multiple' : ''}${this.getAttribute('accept') ? ` accept="${escapeHtml(this.getAttribute('accept'))}"` : ''}${this.getAttribute('capture') ? ` capture="${escapeHtml(this.getAttribute('capture'))}"` : ''}${this.hasAttribute('disabled') ? ' disabled' : ''}></label><div part="previews">${this.#results.map((result, index) => `<article>${result.previewUrl ? `<img src="${escapeHtml(result.previewUrl)}" alt="">` : `<span>${escapeHtml(fileExtensionLabel(result.file.name))}</span>`}<span>${escapeHtml(result.file.name)}</span><button type="button" data-remove="${index}" aria-label="Remove ${escapeHtml(result.file.name)}">Remove</button></article>`).join('')}</div>`; this.#root.querySelector<HTMLInputElement>('input')?.addEventListener('change', event => this.addFiles((event.currentTarget as HTMLInputElement).files ?? [])); this.#root.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(button => button.addEventListener('click', () => this.remove(Number(button.dataset.remove)))); this.addEventListener('dragover', event => event.preventDefault(), { once: true }); this.addEventListener('drop', event => { event.preventDefault(); this.addFiles(event.dataTransfer?.files ?? []); }, { once: true }); } }
export interface FilePreviewData { file: File; previewUrl?: string | null; }
export class FilePreviewDialogComponent extends HTMLElementBase { data: FilePreviewData | null = null; #root: ShadowRoot | null = null; connectedCallback(): void { if (!this.#root) this.#root = this.attachShadow({ mode: 'open' }); this.render(); } render(): void { if (!this.#root) return; const data = this.data; this.#root.innerHTML = `<section role="dialog" aria-label="File preview">${data?.previewUrl ? `<img src="${escapeHtml(data.previewUrl)}" alt="Preview of ${escapeHtml(data.file.name)}">` : `<p>${escapeHtml(data?.file.name ?? 'No file selected')}</p>`}<a${data?.previewUrl ? ` href="${escapeHtml(data.previewUrl)}" download="${escapeHtml(data.file.name)}"` : ' hidden'}>Download</a><slot name="actions"></slot></section>`; } }
export class CameraCaptureDialogComponent extends HTMLElementBase { mediaDevices: MediaDevices | null = globalThis.navigator?.mediaDevices ?? null; #root: ShadowRoot | null = null; #stream: MediaStream | null = null; static supported(mediaDevices: MediaDevices | undefined = globalThis.navigator?.mediaDevices): boolean { return typeof mediaDevices?.getUserMedia === 'function'; } connectedCallback(): void { if (!this.#root) this.#root = this.attachShadow({ mode: 'open' }); this.#root.innerHTML = '<section role="dialog" aria-label="Camera capture"><video autoplay playsinline></video><button type="button" data-capture>Capture</button><canvas hidden></canvas></section>'; this.#root.querySelector('[data-capture]')?.addEventListener('click', () => this.capture()); } disconnectedCallback(): void { this.stop(); } async start(): Promise<boolean> { if (!CameraCaptureDialogComponent.supported(this.mediaDevices ?? undefined)) return false; this.#stream = await this.mediaDevices!.getUserMedia({ video: { facingMode: 'environment' }, audio: false }); const video = this.#root?.querySelector('video'); if (video) video.srcObject = this.#stream; return true; } capture(): File | null { const video = this.#root?.querySelector('video'); const canvas = this.#root?.querySelector('canvas'); if (!video || !canvas || video.videoWidth <= 0) return null; canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0); const data = canvas.toDataURL('image/jpeg'); const bytes = Uint8Array.from(atob(data.split(',')[1] ?? ''), char => char.charCodeAt(0)); const file = new File([bytes], `camera-${Date.now()}.jpg`, { type: 'image/jpeg' }); this.dispatchEvent(new CustomEvent('capture', { bubbles: true, composed: true, detail: { file } })); return file; } stop(): void { for (const track of this.#stream?.getTracks() ?? []) track.stop(); this.#stream = null; const video = this.#root?.querySelector('video'); if (video) video.srcObject = null; } }
export const AFRICANIES_EXTERNAL_ELEMENTS = Object.freeze({ 'africanies-address-input': AddressInputComponent, 'africanies-file-upload': FileUploadComponent, 'africanies-file-preview-dialog': FilePreviewDialogComponent, 'africanies-camera-capture-dialog': CameraCaptureDialogComponent });

export const ANGULAR_FRAMEWORK_DIFFERENCES = Object.freeze([
  { angular: 'NgModule/provider functions', vanilla: 'explicit constructors and defineAfricaniesElements()', status: 'translated' },
  { angular: 'ControlValueAccessor', vanilla: 'form-associated custom elements with value/input/change', status: 'translated' },
  { angular: 'RouterLink/ActivatedRoute directives', vanilla: 'href, History adapters and route helpers', status: 'translated' },
  { angular: 'content directives (TabDef, StepDef, cell/header/detail defs)', vanilla: 'properties, callbacks and named slots', status: 'translated' },
  { angular: 'CDK Overlay and injection tokens', vanilla: 'ModalService/DrawerService contexts and AfricaniesOverlayRef', status: 'translated' },
  { angular: 'header/tooltip/popover/action-menu trigger directives', vanilla: 'named slots and explicit trigger custom elements', status: 'translated' }
]);
