import type { DrawerService, AfricaniesOverlayRef } from './overlay.js';
import { withAfricaniesShadowStyles } from './styles.js';
type HTMLElementConstructor = typeof HTMLElement;
const HTMLElementBase: HTMLElementConstructor = (globalThis.HTMLElement ?? class {}) as HTMLElementConstructor;
const esc = (value: unknown): string => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
abstract class MiscElement extends HTMLElementBase { protected root: ShadowRoot | null = null; connectedCallback(): void { if (!this.root && typeof this.attachShadow === 'function') this.root = this.attachShadow({ mode: 'open' }); this.render(); } attributeChangedCallback(): void { this.render(); } protected abstract render(): void; protected html(value: string): void { if (this.root) this.root.innerHTML = withAfricaniesShadowStyles(value); } }

export interface ActionMenuItem { id: string; label: string; disabled?: boolean; danger?: boolean; }
export class ActionMenuComponent extends MiscElement {
  #items: readonly ActionMenuItem[] = []; #open = false;
  #click = (event: Event): void => { const target = (event.target as Element).closest?.('[data-action]') as HTMLElement | null; if (!target) return; this.dispatchEvent(new CustomEvent('action-select', { bubbles: true, composed: true, detail: { id: target.dataset.action } })); this.open = false; };
  #keydown = (event: KeyboardEvent): void => { if (event.key === 'Escape') { this.open = false; return; } const items = [...(this.root?.querySelectorAll<HTMLElement>('[role="menuitem"]') ?? [])]; if (!['ArrowDown', 'ArrowUp'].includes(event.key) || items.length === 0) return; event.preventDefault(); const current = items.indexOf(this.root?.activeElement as HTMLElement); items[(current + (event.key === 'ArrowDown' ? 1 : -1) + items.length) % items.length]?.focus(); };
  set items(value: readonly ActionMenuItem[]) { this.#items = value; this.render(); } set open(value: boolean) { this.#open = value; this.render(); } get open(): boolean { return this.#open; }
  connectedCallback(): void { super.connectedCallback(); this.root?.addEventListener('click', this.#click); this.addEventListener('keydown', this.#keydown); }
  disconnectedCallback(): void { this.root?.removeEventListener('click', this.#click); this.removeEventListener('keydown', this.#keydown); }
  protected render(): void { this.html(`<div role="menu"${this.#open ? '' : ' hidden'}>${this.#items.map(item => `<button role="menuitem" data-action="${esc(item.id)}"${item.disabled ? ' disabled' : ''}${item.danger ? ' data-danger="true"' : ''}>${esc(item.label)}</button>`).join('')}</div>`); }
}
export class ActionMenuTriggerComponent extends MiscElement { #click = (): void => { this.dispatchEvent(new CustomEvent('menu-toggle', { bubbles: true, composed: true })); }; connectedCallback(): void { super.connectedCallback(); this.root?.addEventListener('click', this.#click); } disconnectedCallback(): void { this.root?.removeEventListener('click', this.#click); } protected render(): void { this.html('<button part="trigger" type="button" aria-haspopup="menu"><slot></slot></button>'); } }

export class AvatarComponent extends MiscElement { static readonly observedAttributes = ['src', 'name', 'size']; protected render(): void { const src = this.getAttribute('src'); const name = this.getAttribute('name') ?? ''; const initials = name.split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase(); this.html(`<span part="avatar" data-size="${esc(this.getAttribute('size') ?? 'medium')}" role="img" aria-label="${esc(name || 'User')}">${src ? `<img src="${esc(src)}" alt="">` : esc(initials || '?')}</span>`); } }
export class AvatarMenuComponent extends ActionMenuComponent {}
export class BrandLogoComponent extends MiscElement { static readonly observedAttributes = ['src', 'alt']; protected render(): void { this.html(`<img part="logo" src="${esc(this.getAttribute('src') ?? '')}" alt="${esc(this.getAttribute('alt') ?? 'AFRICANIES')}">`); } }
export class ImageFallbackFrameComponent extends MiscElement { static readonly observedAttributes = ['src', 'alt', 'fallback']; #error = (): void => { const image = this.root?.querySelector('img'); if (image) image.hidden = true; const fallback = this.root?.querySelector<HTMLElement>('[part="fallback"]'); if (fallback) fallback.hidden = false; }; connectedCallback(): void { super.connectedCallback(); this.root?.querySelector('img')?.addEventListener('error', this.#error); } disconnectedCallback(): void { this.root?.querySelector('img')?.removeEventListener('error', this.#error); } protected render(): void { this.html(`<img part="image" src="${esc(this.getAttribute('src') ?? '')}" alt="${esc(this.getAttribute('alt') ?? '')}"><span part="fallback" hidden>${esc(this.getAttribute('fallback') ?? 'Image unavailable')}</span>`); } }
export const normalizeCarrierName = (value: string): string => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-');
export const carrierLogoUrl = (carrier: string, baseUrl = '/assets/carriers'): string => `${baseUrl.replace(/\/$/, '')}/${normalizeCarrierName(carrier)}.svg`;
export class CarrierLogoComponent extends MiscElement { static readonly observedAttributes = ['carrier', 'base-url']; protected render(): void { const carrier = this.getAttribute('carrier') ?? ''; this.html(`<img part="logo" src="${esc(carrierLogoUrl(carrier, this.getAttribute('base-url') ?? undefined))}" alt="${esc(carrier)} logo">`); } }

export class TooltipComponent extends MiscElement { static readonly observedAttributes = ['message']; protected render(): void { this.html(`<span part="trigger" tabindex="0" aria-describedby="tooltip"><slot></slot></span><span part="tooltip" id="tooltip" role="tooltip">${esc(this.getAttribute('message') ?? '')}</span>`); } }
export class InfoPopoverComponent extends MiscElement { static readonly observedAttributes = ['open']; #click = (): void => { this.toggleAttribute('open'); }; connectedCallback(): void { super.connectedCallback(); this.root?.querySelector('button')?.addEventListener('click', this.#click); } disconnectedCallback(): void { this.root?.querySelector('button')?.removeEventListener('click', this.#click); } protected render(): void { const open = this.hasAttribute('open'); this.html(`<button type="button" aria-expanded="${open}" aria-controls="popover"><slot name="trigger">Info</slot></button><div id="popover" role="dialog"${open ? '' : ' hidden'}><slot></slot></div>`); } }
export class AppShellComponent extends MiscElement { protected render(): void { this.html('<div part="shell"><slot name="side-nav"></slot><div part="main"><slot name="header"></slot><main><slot></slot></main></div></div>'); } }
export class HeaderComponent extends MiscElement { protected render(): void { this.html('<header><slot name="start"></slot><slot></slot><slot name="end"></slot></header>'); } }
export class ContentHeaderComponent extends MiscElement { static readonly observedAttributes = ['heading', 'description']; protected render(): void { this.html(`<header><div><h2>${esc(this.getAttribute('heading') ?? '')}</h2>${this.getAttribute('description') ? `<p>${esc(this.getAttribute('description'))}</p>` : ''}</div><slot name="actions"></slot></header>`); } }

export interface NotificationPage<T = unknown> { data: readonly T[]; has_next_page?: boolean; }
export interface NotificationAdapter<T = unknown> { list(page: number): Promise<NotificationPage<T>>; markRead?(id: string): Promise<unknown>; }
export class NotificationDrawerService<T = unknown> {
  constructor(private readonly drawer: DrawerService, private readonly adapter: NotificationAdapter<T>) {}
  open(): AfricaniesOverlayRef<unknown> { return this.drawer.open(({ document }) => { const panel = document.createElement('africanies-notification-drawer') as NotificationDrawerComponent<T>; panel.adapter = this.adapter; return panel; }, { dismissible: true }); }
}
export class NotificationDrawerComponent<T = unknown> extends MiscElement { adapter: NotificationAdapter<T> | null = null; #items: T[] = []; #page = 0; #loading = false; async loadMore(): Promise<void> { if (!this.adapter || this.#loading) return; this.#loading = true; this.render(); try { const page = await this.adapter.list(this.#page + 1); this.#page += 1; this.#items.push(...page.data); } finally { this.#loading = false; this.render(); } } protected render(): void { this.html(`<section aria-label="Notifications" aria-busy="${this.#loading}"><slot name="header"></slot><div part="items">${this.#items.map(item => `<div part="item">${esc(JSON.stringify(item))}</div>`).join('')}</div><button type="button" part="load-more"${this.#loading ? ' disabled' : ''}>Load more</button></section>`); this.root?.querySelector('[part="load-more"]')?.addEventListener('click', () => void this.loadMore()); } }

export class FilterQueryService { constructor(private readonly history?: History, private readonly location?: Location) {} read(): Record<string, string> { return Object.fromEntries(new URLSearchParams(this.location?.search ?? '')); } write(values: Record<string, unknown>, replace = true): void { const query = new URLSearchParams(); for (const [key, value] of Object.entries(values)) if (value != null && value !== '') query.set(key, String(value)); const url = `${this.location?.pathname ?? ''}${query.size ? `?${query}` : ''}`; if (replace) this.history?.replaceState(null, '', url); else this.history?.pushState(null, '', url); } clear(): void { this.write({}); } }
export interface FilterResolverAdapter { resolve(config: unknown): Promise<unknown>; }
export class FilterDrawerService { constructor(private readonly drawer: DrawerService, private readonly query: FilterQueryService, private readonly resolver?: FilterResolverAdapter) {} open(config: unknown): AfricaniesOverlayRef<Record<string, unknown>> { return this.drawer.open(({ document, ref }) => { const panel = document.createElement('africanies-filter-drawer') as FilterDrawerComponent; panel.initial = this.query.read(); panel.resolveOptions = () => this.resolver?.resolve(config) ?? Promise.resolve(undefined); panel.addEventListener('filter-apply', event => { const values = (event as CustomEvent<Record<string, unknown>>).detail; this.query.write(values); ref.close(values); }); return panel; }, { dismissible: true }); } }
export class FilterDrawerComponent extends MiscElement { initial: Record<string, unknown> = {}; resolveOptions: (() => Promise<unknown>) | null = null; apply(values: Record<string, unknown>): void { this.dispatchEvent(new CustomEvent('filter-apply', { bubbles: true, composed: true, detail: values })); } protected render(): void { this.html('<section aria-label="Filters"><slot></slot><div part="actions"><button type="button" data-action="clear">Clear</button><button type="button" data-action="apply">Apply</button></div></section>'); } }

export const AFRICANIES_MISC_ELEMENTS = Object.freeze({ 'africanies-action-menu': ActionMenuComponent, 'africanies-action-menu-trigger': ActionMenuTriggerComponent, 'africanies-avatar': AvatarComponent, 'africanies-avatar-menu': AvatarMenuComponent, 'africanies-brand-logo': BrandLogoComponent, 'africanies-image-fallback-frame': ImageFallbackFrameComponent, 'africanies-carrier-logo': CarrierLogoComponent, 'africanies-tooltip': TooltipComponent, 'africanies-info-popover': InfoPopoverComponent, 'africanies-app-shell': AppShellComponent, 'africanies-header': HeaderComponent, 'africanies-content-header': ContentHeaderComponent, 'africanies-notification-drawer': NotificationDrawerComponent, 'africanies-filter-drawer': FilterDrawerComponent });
