const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);
const icon = n => `<span class="demo-icon" aria-hidden="true">${({add:'+',close:'×',info:'i',warning:'!',success:'✓',search:'⌕',menu:'⋮',arrow:'→',copy:'⧉'})[n] ?? '◇'}</span>`;
const btn = (label, variant='primary', attrs='') => `<button class="sdk-button ${variant}" type="button" ${attrs}>${label}</button>`;
const code = v => `<pre class="relative mt-5 overflow-auto rounded-lg bg-slate-900 p-5 leading-6 text-slate-200"><code>${esc(v)}</code><button class="copy-code" data-copy="${esc(v)}" aria-label="Copy code">${icon('copy')}</button></pre>`;
const page = (eyebrow,title,description,content) => `<article class="page-enter"><header class="page-heading"><p class="eyebrow">${eyebrow}</p><h2 class="mb-3 text-[38px] font-bold leading-[1.12] tracking-[-.035em] max-[520px]:text-3xl">${title}</h2><p class="m-0 leading-7 text-slate-500 dark:text-slate-400">${description}</p></header>${content}${executableDemos[title]?.() ?? ''}</article>`;
const demo = (title,description,body,marker='') => `<section class="demo-card" ${marker}><div class="demo-copy"><span class="mb-2 inline-flex rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-slate-600 dark:bg-slate-800 dark:text-slate-300">${title.startsWith('SDK ') ? 'SDK executable' : 'Host composition'}</span><h3 class="mb-1.5 text-lg font-bold">${title}</h3><p class="m-0 leading-7 text-slate-500 dark:text-slate-400">${description}</p></div><div class="demo-stage">${body}</div></section>`;

const executable = (title, body, sample) => demo(title, 'This example executes the registered Vanilla SDK contract.', `<div class="stack" data-sdk-executable>${body}</div>${code(sample)}`);
const executableDemos = {
  'Build logistics experiences, faster.': () => executable('SDK notification drawer', `${btn('Open notification drawer','secondary','data-sdk-notifications')}<africanies-notification-drawer data-sdk-notification-panel></africanies-notification-drawer>`, 'new NotificationDrawerService(drawer, adapter).open();'),
  Alert: () => executable('SDK alert', '<africanies-alert variant="success" heading="SDK success" dismissible>Rendered by the registered alert custom element.</africanies-alert>', '<africanies-alert variant="success" dismissible>Saved</africanies-alert>'),
  Chip: () => executable('SDK chip', '<africanies-chip variant="info" removable>In transit</africanies-chip>', '<africanies-chip variant="info" removable>In transit</africanies-chip>'),
  'Action menu': () => executable('SDK action menu', '<africanies-action-menu data-sdk-action-menu></africanies-action-menu>', 'menu.items = [{ id: "view", label: "View shipment" }];'),
  Feedback: () => executable('SDK async states', '<africanies-loading heading="Loading shipments" message="Please wait"></africanies-loading><africanies-empty heading="No shipments"></africanies-empty><africanies-error heading="Unable to load" message="Try again"></africanies-error><africanies-async-state state="success"><span>Loaded with the SDK state wrapper.</span></africanies-async-state>', '<africanies-async-state state="loading"></africanies-async-state>'),
  Overlays: () => executable('SDK overlay services', `${btn('Open SDK modal','primary','data-sdk-overlay="modal"')}${btn('Open SDK drawer','secondary','data-sdk-overlay="drawer"')}${btn('Open SDK confirm','danger','data-sdk-overlay="confirm"')}${btn('Async error then retry','danger','data-sdk-confirm-retry')}<output id="sdk-confirm-output" class="font-mono text-xs"></output>`, 'confirmService.confirm({ message, onConfirm: async () => save() });'),
  Forms: () => executable('SDK form controls', '<form data-sdk-form class="stack"><africanies-text-input name="shipment" label="Shipment name" required></africanies-text-input><africanies-textarea name="notes" label="Notes"></africanies-textarea><africanies-number-input name="weight" label="Weight" min="0"></africanies-number-input><africanies-date-picker name="pickup" label="Pickup date"></africanies-date-picker><africanies-checkbox name="confirmed" label="Confirmed"></africanies-checkbox><africanies-radio name="speed" value="express" label="Express"></africanies-radio><africanies-toggle name="insured" label="Insured"></africanies-toggle><africanies-otp-input name="otp" label="Verification code" length="6"></africanies-otp-input><africanies-select name="service" label="Service" data-sdk-select></africanies-select><africanies-search-combobox name="country" label="Country" data-sdk-combobox></africanies-search-combobox><button class="sdk-button primary" data-sdk-form-submit>Read FormData</button></form><output id="sdk-form-output" class="font-mono text-xs"></output>', 'select.options = [{ label: "Express", value: "express" }];'),
  Filters: () => executable('SDK filter drawer and query helpers', `${btn('Open SDK filter drawer','primary','data-sdk-filter-drawer')}${btn('Apply SDK filters','secondary','data-sdk-filter-apply')}${btn('Clear SDK filters','secondary','data-sdk-filter-clear')}<africanies-filter-drawer data-sdk-filter-panel></africanies-filter-drawer><output id="sdk-filter-output" class="font-mono text-xs"></output>`, 'new FilterDrawerService(drawer, query, resolver).open(config);'),
  Tooltip: () => executable('SDK tooltip', '<africanies-tooltip message="Live SDK tooltip"><button class="sdk-button secondary">Focus or hover</button></africanies-tooltip>', '<africanies-tooltip message="Helpful context">…</africanies-tooltip>'),
  Toast: () => executable('SDK ToastService and HTTP context', `${btn('SDK success','primary','data-sdk-toast="success"')}${btn('Stack duplicate','secondary','data-sdk-toast="stack"')}${btn('Persistent error','danger','data-sdk-toast="error"')}${btn('Build withToast options','secondary','data-sdk-with-toast')}<output id="sdk-with-toast-output" class="font-mono text-xs"></output>`, 'client.post(path, body, withToast({ successMessage: "Saved" }));'),
  Table: () => executable('SDK table and pagination', '<africanies-table data-sdk-table></africanies-table><africanies-pagination page="1" page-size="10" total="23"></africanies-pagination>', 'table.columns = columns; table.rows = shipments;'),
  Stepper: () => executable('SDK stepper', '<africanies-stepper data-sdk-stepper></africanies-stepper>', 'stepper.steps = [{ id: "address", label: "Address" }];'),
  'Navigation · Overview': () => executable('SDK navigation and app-shell family', '<africanies-app-shell><africanies-app-shell-header slot="header" user-name="Amara Okafor" show-clock="false"></africanies-app-shell-header><africanies-app-shell-content-header title="Shipments" subtitle="SDK content header" back-href="#/overview"></africanies-app-shell-content-header></africanies-app-shell><africanies-breadcrumb data-sdk-breadcrumb></africanies-breadcrumb><africanies-tabs data-sdk-tabs></africanies-tabs><africanies-segment data-sdk-segment></africanies-segment><output id="sdk-parent-output" class="font-mono text-xs"></output><output id="sdk-greeting-output" class="font-mono text-xs"></output>', 'resolveParentPathFromRootSnapshot(snapshot); pickHeaderGreeting(name, now);'),
  'Navigation · Documents': () => executable('SDK navigation elements', '<africanies-tabs data-sdk-tabs></africanies-tabs>', 'tabs.selected = "documents";'),
  'Navigation · Events': () => executable('SDK navigation elements', '<africanies-tabs data-sdk-tabs></africanies-tabs>', 'tabs.selected = "events";'),
  Icons: () => executable('SDK icon registry', `${btn('Load SDK sprite','secondary','data-sdk-icons')}<output id="sdk-icon-output"></output>`, 'await new IconRegistryService({ document, fetch }).ensureLoaded();'),
  Models: () => executable('SDK model helpers', '<output id="sdk-model-output" class="font-mono text-xs"></output>', 'normalizeDeliveryVendorForForm({ name: "DHL" });'),
  'SDK API': () => executable('SDK runtime helpers', '<output id="sdk-api-output" class="font-mono text-xs"></output>', 'isValidEmail("ops@africanies.com"); toCsvString(rows);')
};

const overview = () => page('AFRICANIES WEB SDK','Build logistics experiences, faster.','Framework-independent primitives, services and patterns for dependable shipping products.',`
 <section class="hero-grid"><div class="hero-actions"><a class="sdk-button primary" href="#/components/button">Explore components →</a><a class="text-link" href="#/api">Read API reference</a></div><div class="hero-panel"><span class="status-dot"></span><strong>SDK ready</strong><p>Vanilla JavaScript · ESM · CDN</p></div></section>
 <section class="stats"><div><strong>26</strong><span>Playground routes</span></div><div><strong>6</strong><span>SDK packages</span></div><div><strong>0</strong><span>Framework dependencies</span></div></section>
 <section class="catalog"><div class="section-title"><div><p class="eyebrow">CATALOG</p><h3>Explore the toolkit</h3></div><a href="#/components/button">View components →</a></div><div class="catalog-grid">${[['Components','Buttons, forms, feedback, navigation and overlays.','/components/button'],['Use cases','Shipment and onboarding workflows ready to inspect.','/usecases/shipment'],['Foundations','Tokens, icons, models and API contracts.','/tokens']].map(([t,c,h])=>`<a class="catalog-card" href="#${h}"><span class="catalog-symbol">◇</span><h4>${t}</h4><p>${c}</p><span>Explore ${icon('arrow')}</span></a>`).join('')}</div></section>`);

const buttons = () => page('COMPONENTS','Button','Actions communicate what happens next and preserve native keyboard behavior.',`
 ${demo('Variants','Use visual emphasis to establish action hierarchy.',`<div class="row wrap">${btn('Primary')}${btn('Secondary','secondary')}${btn('Ghost primary','ghost-primary')}${btn('Danger','danger')}${btn('Underline','underline')}</div>`,'data-demo="button-variants"')}
 ${demo('Sizes and states','Three sizes with loading and disabled states.',`<div class="row wrap">${btn('Small','primary small')}${btn('Medium')}${btn('Large','secondary large')}${btn('<span class="spinner"></span> Saving','primary','disabled')}${btn('Unavailable','secondary','disabled')}</div>`)}
 ${demo('SDK custom element','The playground registers and demonstrates the actual Vanilla SDK.',`<africanies-button variant="primary">SDK button</africanies-button>${code('<africanies-button variant="primary">SDK button</africanies-button>')}`)}`);

const alerts = () => page('COMPONENTS','Alert','Contextual messages keep people informed without interrupting their work.',demo('Variants','Informational, successful, warning and error messages.',`<div class="stack">${[['info','Information','Shipment estimates update every 15 minutes.'],['success','Shipment booked','Your tracking number is ready.'],['warning','Customs documents required','Upload the commercial invoice to continue.'],['danger','Unable to book shipment','Review the highlighted details and try again.']].map(([tone,title,msg])=>`<div class="alert ${tone}" role="${tone==='warning'||tone==='danger'?'alert':'status'}">${icon(tone==='danger'?'warning':tone)}<div><strong>${title}</strong><p>${msg}</p></div><button class="icon-button dismiss-alert" aria-label="Dismiss alert">×</button></div>`).join('')}</div>`,'data-demo="alert-states"'));
const chips = () => page('COMPONENTS','Chip','Compact labels describe statuses, filters and removable selections.',`${demo('Status chips','Use semantic tones consistently.',`<div class="row wrap"><span class="chip neutral">Draft</span><span class="chip info">In transit</span><span class="chip success">Delivered</span><span class="chip warning">Delayed</span><span class="chip danger">Cancelled</span></div>`)}${demo('Removable','Selected filters can be removed independently.',`<div class="row wrap"><span class="chip neutral">Lagos <button class="remove-chip" aria-label="Remove Lagos">×</button></span><span class="chip neutral">Air freight <button class="remove-chip" aria-label="Remove Air freight">×</button></span></div>`)}`);
const actionMenu = () => page('COMPONENTS','Action menu','Keep secondary actions available without crowding the interface.',demo('Menu','Open the menu and navigate its actions with the keyboard.',`<div class="menu-demo"><button class="sdk-button secondary" data-action-menu aria-haspopup="menu" aria-expanded="false">Shipment actions ${icon('menu')}</button><div class="popover" role="menu" hidden><button role="menuitem">View shipment</button><button role="menuitem">Duplicate</button><button role="menuitem">Download documents</button><button class="danger-text" role="menuitem">Cancel shipment</button></div></div>`));
const feedback = () => page('COMPONENTS','Feedback','Consistent states explain what the interface is doing and what to do next.',demo('State playground','Switch between the complete async state family.',`<div class="segmented" role="group" aria-label="Feedback state"><button data-feedback="loading" aria-pressed="true">Loading</button><button data-feedback="empty" aria-pressed="false">Empty</button><button data-feedback="error" aria-pressed="false">Error</button><button data-feedback="success" aria-pressed="false">Success</button></div><div id="feedback-preview" class="feedback-state"><span class="large-spinner"></span><strong>Loading shipments</strong><p>This will only take a moment.</p></div>`,'data-demo="feedback-states"'));
const overlays = () => page('COMPONENTS','Overlays','Dialogs and drawers focus attention while preserving context.',demo('Modal, confirmation and drawer','Focus is contained and restored on close.',`<div class="row wrap">${btn('Open modal','primary','data-open-overlay="modal"')}${btn('Open confirmation','secondary','data-open-overlay="confirm"')}${btn('Open drawer','secondary','data-open-overlay="drawer"')}</div>`,'data-demo="overlay-states"'));
const forms = () => page('COMPONENTS','Forms','Accessible controls support labels, hints, validation and progressive disclosure.',demo('Shipment details','A representative collection of field states.',`<form class="form-grid" data-demo="form-states"><label><span>Shipment name</span><input name="name" placeholder="e.g. Lagos weekly stock" required><small>Give this shipment a memorable name.</small></label><label><span>Service</span><select><option>Express air</option><option>Standard air</option><option>Ocean freight</option></select></label><label><span>Tracking number</span><input value="AFR-102948" readonly><small>Read-only value</small></label><label><span>Contact email</span><input type="email" value="invalid-email" aria-invalid="true"><small class="field-error">Enter a valid email address.</small></label><label class="wide"><span>Notes</span><textarea placeholder="Delivery instructions"></textarea></label><label class="check wide"><input type="checkbox"> <span>I confirm the shipment details are correct.</span></label>${btn('Save details','primary','data-demo-submit')}</form>`));
const filters = () => page('COMPONENTS','Filters','Narrow datasets while making active constraints visible and reversible.',demo('Shipment filters','Apply, inspect and clear active filters.',`<div class="filter-bar"><label class="search">${icon('search')}<input placeholder="Search shipments"></label><select aria-label="Status"><option>All statuses</option><option>In transit</option><option>Delivered</option></select>${btn('Apply filters')}<button class="text-button" data-clear-filters>Clear all</button></div><div class="row"><span class="chip info">Export ×</span><span class="chip neutral">Last 30 days ×</span></div>`));
const tooltip = () => page('COMPONENTS','Tooltip','Brief labels clarify unfamiliar controls on hover and keyboard focus.',demo('Positions','Hover or focus each trigger.',`<div class="row tooltip-row"><button class="icon-button tooltip-trigger" aria-describedby="tip-top">?</button><span role="tooltip" id="tip-top">Helpful context</span><button class="sdk-button secondary tooltip-trigger" aria-describedby="tip-action">Track shipment</button><span role="tooltip" id="tip-action">Opens live tracking</span></div>`));
const toast = () => page('COMPONENTS','Toast','Temporary notifications confirm actions without blocking the workflow.',demo('Variants','Notifications appear in the top-right region and remain keyboard accessible.',`<div class="row wrap">${btn('Show success','primary','data-toast="success"')}${btn('Show information','secondary','data-toast="info"')}${btn('Show warning','secondary','data-toast="warning"')}${btn('Show error','danger','data-toast="danger"')}</div>`,'data-demo="toast-states"'));

const tableBody = () => `<div class="table-tools"><label class="search">${icon('search')}<input placeholder="Search by tracking number"></label>${btn('Export CSV','secondary')}</div><div class="table-wrap" data-demo="table-states"><table><thead><tr><th><button data-sort>Status ↕</button></th><th>Tracking</th><th>Route</th><th><button data-sort>Updated ↕</button></th><th></th></tr></thead><tbody>${[['In transit','AFR-102948','LOS → NBO','Today, 09:42'],['Delivered','AFR-102771','ACC → LOS','Yesterday'],['Delayed','AFR-102690','NBO → CPT','22 Aug 2026']].map(([s,id,r,d],i)=>`<tr><td><span class="chip ${i===1?'success':i===2?'warning':'info'}">${s}</span></td><td><a href="#/usecases/shipment/${id}">${id}</a></td><td>${r}</td><td>${d}</td><td><button class="icon-button" aria-label="Actions for ${id}">⋮</button></td></tr>`).join('')}</tbody></table></div><nav class="pagination" aria-label="Pagination"><button disabled>Previous</button><span>Page 1 of 3</span><button>Next</button></nav>`;
const table = () => page('COMPONENTS','Table','Structured shipping data supports scanning, sorting and row actions.',demo('Shipment table','Sort columns and inspect a shipment.',tableBody()));
const stepper = () => page('COMPONENTS','Stepper','Communicate progress through a bounded multi-step workflow.',demo('Create shipment','Completed, active and upcoming steps.',`<ol class="stepper"><li class="complete"><span>✓</span><div><strong>Addresses</strong><small>Pickup and delivery</small></div></li><li class="active"><span>2</span><div><strong>Package</strong><small>Weight and dimensions</small></div></li><li><span>3</span><div><strong>Service</strong><small>Delivery option</small></div></li><li><span>4</span><div><strong>Review</strong><small>Confirm and pay</small></div></li></ol>`));
const navigation = active => page('COMPONENTS',`Navigation · ${active}`,'Nested navigation, breadcrumbs and tabs keep location clear.',demo('Account navigation','Tabs preserve route semantics and keyboard behavior.',`<nav class="tabs" aria-label="Account sections">${['Overview','Documents','Events'].map(x=>`<a ${active===x?'aria-current="page"':''} href="#/components/navigation/${x.toLowerCase()}">${x}</a>`).join('')}</nav><div class="tab-panel"><h4>${active}</h4><p>${active==='Overview'?'A concise view of account activity and shipment health.':active==='Documents'?'Commercial invoices, labels and customs documents.':'A chronological record of account and shipment events.'}</p></div>`));
const shipment = () => page('USE CASE','Shipments','Track active shipments and quickly identify exceptions.',`<div class="usecase-header"><div><span class="text-[10px] font-bold uppercase">Host composition + SDK data primitive</span><h3>All shipments</h3><p>12 shipments updated in the last 30 days.</p></div>${btn(`${icon('add')} Create shipment`,'primary','data-toast="info"')}</div><div data-demo="shipment-workflow">${tableBody()}</div>${executable('SDK shipment table','<africanies-table data-sdk-table></africanies-table><africanies-pagination page="1" page-size="10" total="12"></africanies-pagination>','table.rows = normalizedPagination.data;')}`);
const shipmentDetail = ({id}) => page('USE CASE',`Shipment ${esc(id)}`,'Live delivery progress and shipment documentation.',`<span class="text-[10px] font-bold uppercase">Host composition using routed model data</span><a class="back-link" href="#/usecases/shipment">← All shipments</a><africanies-page-header heading="Shipment ${esc(id)}" description="SDK page header"></africanies-page-header><section class="shipment-summary"><div><span class="chip info">In transit</span><h3>Lagos to Nairobi</h3><p>${esc(id)} · Express air</p></div>${btn('Track live','secondary','data-toast="info"')}</section><ol class="timeline"><li class="complete"><strong>Shipment collected</strong><span>Lagos · 26 Aug, 14:20</span></li><li class="complete"><strong>Departed origin facility</strong><span>Lagos · 27 Aug, 07:10</span></li><li class="active"><strong>In transit</strong><span>Expected in Nairobi tomorrow</span></li><li><strong>Delivered</strong><span>Pending</span></li></ol>`);
const onboarding = kind => { const d={login:['Welcome back','Sign in to manage your shipments.','Sign in'],forgot:['Forgot password?','Enter your email and we’ll send reset instructions.','Send reset link'],reset:['Set a new password','Choose a secure password for your account.','Reset password']}[kind]; return page('ONBOARDING',d[0],d[1],`<div class="auth-card" data-demo="onboarding-flow"><span class="text-[10px] font-bold uppercase">SDK form controls · simulated host submit</span><form data-sdk-form><africanies-text-input name="email" type="email" label="Email address" placeholder="name@company.com" required></africanies-text-input>${kind!=='forgot'?'<africanies-text-input name="password" type="password" label="Password" required></africanies-text-input>':''}${kind==='reset'?'<africanies-text-input name="confirmation" type="password" label="Confirm password" required></africanies-text-input>':''}${btn(d[2],'primary','data-sdk-form-submit')}</form><output id="sdk-form-output" class="font-mono text-xs"></output><a href="#/usecases/onboarding/${kind==='login'?'forgot-password':'login'}">${kind==='login'?'Forgot password?':'Back to sign in'}</a></div>`); };
const lecture = () => page('LEARN','Building with the SDK','A guided tour of the package architecture and browser integration.',`<div class="prose"><h3>Start with explicit registration</h3><p>Import the browser bundle, register custom elements once, then use standards-based markup anywhere.</p>${code("import { defineAfricaniesElements } from '@africanies/javascript-web-sdk';\ndefineAfricaniesElements();")}<h3>Compose framework-independent UI</h3><p>Custom elements, services and model contracts do not require Angular at runtime.</p></div>`);
const icons = () => page('FOUNDATIONS','Icons','Search and reuse the visual language across logistics products.',demo('Icon gallery','A representative selection from the AFRICANIES sprite.',`<label class="search icon-search">${icon('search')}<input placeholder="Search 638 icons" data-icon-search></label><div class="icon-grid" data-demo="icon-gallery">${['add','arrow','close','copy','info','menu','search','success','warning','package','truck','user','calendar','download','filter','location'].map(n=>`<button data-icon-name="${n}"><span>${icon(n)}</span><small>${n}</small></button>`).join('')}</div>`));
const tokens = () => page('FOUNDATIONS','Design tokens','Color, type, space and elevation provide a coherent visual foundation.',`<section class="token-grid">${[['Primary','#0047bb'],['Success','#15803d'],['Warning','#b54708'],['Danger','#b42318'],['Surface','#ffffff'],['Canvas','#f4f6f8']].map(([n,v])=>`<div class="token"><span style="background:${v}"></span><strong>${n}</strong><code>${v}</code></div>`).join('')}</section>`);
const models = () => page('REFERENCE','Models','Shared contracts make API and UI state predictable.',demo('Shipment model','Framework-neutral data shape.',code(`{\n  "trackingNumber": "AFR-102948",\n  "status": "in_transit",\n  "origin": "LOS",\n  "destination": "NBO"\n}`)));
const api = () => page('REFERENCE','SDK API','Package entry points and browser-first integration.',`<div class="api-list">${['@africanies/javascript-web-sdk','@africanies/africanies-core','@africanies/africanies-models','@africanies/africanies-storage','@africanies/africanies-theme','@africanies/africanies-icons','@africanies/africanies-ui'].map(n=>`<section><code>${n}</code><p>Typed ESM exports for framework-independent applications.</p></section>`).join('')}</div>`);

export const PLAYGROUND_ROUTE_CONFIG = Object.freeze([
 ['/overview',overview],['/components/button',buttons],['/components/alert',alerts],['/components/chip',chips],['/components/action-menu',actionMenu],['/components/feedback',feedback],['/components/overlays',overlays],['/components/forms',forms],['/components/filters',filters],['/components/tooltip',tooltip],['/components/toast',toast],['/components/table',table],['/components/stepper',stepper],['/components/navigation/overview',()=>navigation('Overview')],['/components/navigation/documents',()=>navigation('Documents')],['/components/navigation/events',()=>navigation('Events')],['/usecases/shipment',shipment],['/usecases/shipment/:id',shipmentDetail],['/usecases/onboarding/login',()=>onboarding('login')],['/usecases/onboarding/forgot-password',()=>onboarding('forgot')],['/usecases/onboarding/reset-password',()=>onboarding('reset')],['/lecture',lecture],['/icons',icons],['/tokens',tokens],['/models',models],['/api',api]
].map(([path,render])=>Object.freeze({path,render:(params) => applyUtilities(render(params))})));

export function matchRoute(routePath) {
 for (const route of PLAYGROUND_ROUTE_CONFIG) {
  if (route.path===routePath) return {route,params:{}};
  if (route.path==='/usecases/shipment/:id') { const m=routePath.match(/^\/usecases\/shipment\/([^/]+)$/); if(m) return {route,params:{id:decodeURIComponent(m[1])}}; }
 }
 return null;
}
import { applyUtilities } from './styles.mjs';
